"""Validation of the screening match engine on a labelled test set.

config/matching_testset.json holds name pairs labelled `match` (same person / company:
transliterations, middle names, diacritics, name order, legal forms, typos, same
identifier) or `no_match` (namesakes contradicted by the date of birth, very common
names, generic company words, single-word names, person vs company…). Each pair goes
through the production matcher (app.matching.matcher.match_entities) and is compared
with the thresholds of config/risk.yaml.

Reported, per category and overall:
* detection rate (recall): `match` pairs that raise an alert (score at or above the
  possible-match threshold and not set aside as a probable namesake by the triage);
* strong detection: `match` pairs at or above the strong-match threshold;
* false-positive rate: `no_match` pairs that still raise an alert;
* every error, with the matcher's own explanation.

This is the evidence an auditor asks for: what the engine catches, what it lets through,
and why: regenerated by `python scripts/validation_report.py` and checked in CI.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from functools import lru_cache
from typing import Any

from app import __version__
from app.matching.matcher import match_entities
from app.models import Entity, EntityType, ListType, Provenance, ScreeningHit
from app.risk.config import get_risk_config
from app.settings import CONFIG_DIR
from app.triage import triage

TESTSET = CONFIG_DIR / "matching_testset.json"


def _entity(d: dict[str, Any], key: str) -> Entity:
    return Entity(
        id=key,
        type=EntityType(d["type"]),
        name=d["name"],
        aliases=d.get("aliases", []),
        birth_date=d.get("birth_date"),
        nationalities=d.get("nationalities", []),
        jurisdiction=d.get("jurisdiction"),
        registration_number=d.get("registration_number"),
    )


def _pct(n: int, d: int) -> float | None:
    return round(100 * n / d, 1) if d else None


def run_validation() -> dict[str, Any]:
    data = json.loads(TESTSET.read_text(encoding="utf-8"))
    t = get_risk_config().thresholds
    possible, strong = float(t["possible_match_score"]), float(t["strong_match_score"])
    rows = []
    for i, case in enumerate(data["cases"]):
        q = _entity(case["query"], f"q{i}")
        c = _entity(case["candidate"], f"c{i}")
        result = match_entities(q, c)
        hit = ScreeningHit(
            entity_id=q.id,
            list_type=ListType.SANCTION,
            dataset="validation",
            matched_name=c.name,
            score=result.score,
            explanation=result.explanation,
            provenance=Provenance(source="validation", source_label="validation"),
        )
        label, _ = triage(hit, q)
        # An alert reaches the analyst when the score passes the threshold and the triage
        # does not set it aside as a probable namesake (same rule as in the product).
        flagged = result.score >= possible and label != "namesake"
        expected = case["expected"] == "match"
        rows.append(
            {
                "category": case["category"],
                "query": case["query"]["name"],
                "candidate": case["candidate"]["name"],
                "expected": case["expected"],
                "score": result.score,
                "flagged": flagged,
                "strong": result.score >= strong and label != "namesake",
                "triage": label,
                "correct": flagged == expected,
                "explanation": result.explanation,
                "note": case.get("note", ""),
            }
        )

    def stats(sub: list[dict[str, Any]]) -> dict[str, Any]:
        pos = [r for r in sub if r["expected"] == "match"]
        neg = [r for r in sub if r["expected"] == "no_match"]
        return {
            "pairs": len(sub),
            "match_pairs": len(pos),
            "no_match_pairs": len(neg),
            "detected": sum(r["flagged"] for r in pos),
            "detection_rate": _pct(sum(r["flagged"] for r in pos), len(pos)),
            "strong_detection_rate": _pct(sum(r["strong"] for r in pos), len(pos)),
            "false_positives": sum(r["flagged"] for r in neg),
            "false_positive_rate": _pct(sum(r["flagged"] for r in neg), len(neg)),
            "accuracy": _pct(sum(r["correct"] for r in sub), len(sub)),
        }

    categories = []
    for cat in dict.fromkeys(r["category"] for r in rows):
        sub = [r for r in rows if r["category"] == cat]
        categories.append({"category": cat, "expected": sub[0]["expected"], **stats(sub)})
    return {
        "limits": (
            "Test set written by the development team: a regression guard, not a guarantee on "
            "real data. Extend it with an independent sample of real alerts before production use."
        ),
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "engine_version": __version__,
        "testset_version": data.get("version"),
        "thresholds": {"possible_match": possible, "strong_match": strong},
        "overall": stats(rows),
        "categories": categories,
        "errors": [r for r in rows if not r["correct"]],
        "pairs": rows,
    }


@lru_cache(maxsize=1)
def cached_validation() -> dict[str, Any]:
    return run_validation()


def to_markdown(report: dict[str, Any]) -> str:
    o = report["overall"]
    th = report["thresholds"]
    lines = [
        "# Matching validation report",
        "",
        f"Generated {report['generated_at']} · engine {report['engine_version']} · "
        f"test set v{report['testset_version']} ({o['pairs']} labelled pairs)",
        "",
        f"Thresholds: possible match ≥ {th['possible_match']:g}, strong match ≥ {th['strong_match']:g} "
        "(config/risk.yaml).",
        "",
        "## Overall",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Detection rate (same entity flagged) | **{o['detection_rate']} %** ({o['detected']}/{o['match_pairs']}) |",
        f"| Strong detection (≥ {th['strong_match']:g}) | {o['strong_detection_rate']} % |",
        f"| False-positive rate (different entity flagged) | **{o['false_positive_rate']} %** ({o['false_positives']}/{o['no_match_pairs']}) |",
        f"| Accuracy | {o['accuracy']} % |",
        "",
        "## By category",
        "",
        "| Category | Expected | Pairs | Detection | False positives |",
        "|---|---|---|---|---|",
    ]
    for c in report["categories"]:
        det = f"{c['detection_rate']} %" if c["match_pairs"] else "-"
        fp = f"{c['false_positive_rate']} %" if c["no_match_pairs"] else "-"
        lines.append(
            f"| {c['category']} | {c['expected'].replace('_', ' ')} | {c['pairs']} | {det} | {fp} |"
        )
    lines += ["", "## Errors", ""]
    if not report["errors"]:
        lines.append("None.")
    for e in report["errors"]:
        kind = "missed match" if e["expected"] == "match" else "false positive"
        lines.append(
            f"- **{kind}**: {e['query']} ↔ {e['candidate']} ({e['category']}): score {e['score']:g}, triage {e['triage']}: "
            + "; ".join(e["explanation"])
        )
    lines += [
        "",
        "## Method",
        "",
        "Each pair of the test set (config/matching_testset.json) is scored by the production "
        "matcher and the alert triage, as in the product: a pair raises an alert when its score "
        "reaches the possible-match threshold and the triage does not set it aside as a probable "
        "namesake (different date of birth, nationality, country or name part). The test set mixes public figures "
        "and fictitious names; it is versioned with the code and extended whenever a real-world "
        "error is found. Regenerate with `python scripts/validation_report.py`.",
        "",
        "## Limits",
        "",
        "The pairs were written by the development team to cover known difficulties; a perfect score "
        "on them is a regression guard, not a guarantee on real data. The rates to rely on come from "
        "an independent sample of real alerts reviewed by analysts, to be added to this set before "
        "production use. The engine also depends on the data each list publishes (a missing date of "
        "birth or nationality limits what the triage can rule out).",
        "",
    ]
    return "\n".join(lines)
